branches:
  only:
    - master
language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - build-tools-21.1.1
    - android-21
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

script: ./gradlew connectedAndroidTest

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository