branches:
  only:
    - master

language: android
sudo: false

android:
  components:
    - build-tools-23.0.1
    - android-22
    - doc-23
    - extra-android-support
    - extra-android-m2repository

before_install:
    - pip install --user codecov

after_success:
  - codecov
  - ./scripts/publish_snapshot.sh

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository