branches:
  only:
    - master

language: android
sudo: false

android:
  components:
    - build-tools-23.0.1
    - android-22
    - doc-23
    - extra-android-support
    - extra-android-m2repository

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository