branches:
  only:
    - master
language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - build-tools-23.0.3
    - android-23
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

before_script:
    # Create and start emulator
    - emulator -avd test -no-skin -no-audio -no-window &
    - adb wait-for-device
    - adb shell input keyevent 82 &

script: ./gradlew connectedAndroidTest

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository