branches:
  only:
    - master
env:
  matrix:
    - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a

language: android

android:
  components:
    - build-tools-23.0.1
    - extra-google-m2repository
    - extra-android-m2repository

script: gradle build testReleaseUnitTest