branches:
  only:
    - master
language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools-23.0.1
    - build-tools-23.0.1
    - android-23
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

script:
    - ./gradlew build jacocoTestReport assembleAndroidTest

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository