branches:
  only:
    - master

language: android

android:
  components:
    - platform-tools
    - build-tools
    - android-23
    - add-on
    - extra

script:
  - ./gradlew clean testDebugUnitTest

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository