package com.gms_worldwide.hybersdk;

import com.j256.ormlite.field.DatabaseField;

import java.io.Serializable;

/**
 * Created by Andrew Kochura.
 */
class HyberMessageUpdateDBModel implements Serializable {

    /**
     * The Id.
     */
// id is generated by the database and set on the object automatically
    @DatabaseField(generatedId = true)
    public int id;
    @DatabaseField
    private long time;
    @DatabaseField
    private int type;
    @DatabaseField
    private boolean is_fool_day;

    /**
     * Instantiates a new Hyber message update db model.
     */
    public HyberMessageUpdateDBModel() {

    }

    /**
     * Instantiates a Hyber message update db model.
     *
     * @param time        the time
     * @param type        the type
     * @param is_fool_day the is fool day
     */
    public HyberMessageUpdateDBModel(long time, int type, boolean is_fool_day) {
        this.time = time;
        this.type = type;
        this.is_fool_day = is_fool_day;
    }

    /**
     * Sets is fool day.
     *
     * @param is_fool_day the is fool day
     */
    public void setIs_fool_day(boolean is_fool_day) {
        this.is_fool_day = is_fool_day;
    }

    /**
     * Gets id.
     *
     * @return the id
     */
    public int getId() {
        return id;
    }

    /**
     * Gets time.
     *
     * @return the time
     */
    public long getTime() {
        return time;
    }

    /**
     * Sets time.
     *
     * @param time the time
     */
    public void setTime(long time) {
        this.time = time;
    }

    /**
     * Gets type.
     *
     * @return the type
     */
    public int getType() {
        return type;
    }

    /**
     * Sets type.
     *
     * @param type the type
     */
    public void setType(int type) {
        this.type = type;
    }

    /**
     * Is fool day boolean.
     *
     * @return the boolean
     */
    public boolean is_fool_day() {
        return is_fool_day;
    }

}
